// Generated by CoffeeScript 1.6.1
(function() {
  var form_get, form_set, make_table_from_array, make_table_from_collection;

  form_set = model2rform_make_form.form_set;

  form_get = model2rform_make_form.form_get;

  make_table_from_array = function(template, form_name_parent, form_name_sub, path) {
    template.row = function() {
      var i, linea, obj, ret, _i, _len, _ref;
      obj = form_get(form_name_parent);
      ret = [];
      if (obj[path]) {
        _ref = obj[path];
        for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
          linea = _ref[i];
          if (linea._valid) {
            linea = _.clone(linea);
            linea._path = path + '.' + i;
            ret.push(linea);
          }
        }
      }
      return ret;
    };
    return template.events = {
      'click a.listado': function(e, t) {
        var path_;
        path_ = $(e.target).attr('path');
        return form_set(form_name_sub, path_);
      }
    };
  };

  make_table_from_collection = function(template, collection, search_name, form_name) {
    template.row = function() {
      var selector;
      selector = Session.get(search_name + '_selector');
      return collection.find(selector);
    };
    return template.events = {
      'click a.listado': function(e, t) {
        var _id;
        _id = $(e.target).attr('_id');
        return form_set(form_name, _id);
      }
    };
  };

  this.model2rform_table = {
    make_table_from_array: make_table_from_array,
    make_table_from_collection: make_table_from_collection
  };

}).call(this);
